"use client";

import { useJoyJamSectionInit } from "../use-joyjam-section-init";

export default function JoyJamCta() {
  const ref = useJoyJamSectionInit("cta-sc");

  return (
    <section ref={ref} className="cta-sc">
      <div className="container cta-s"><div {...{ "scroll-scale": "0.8" }} className="cta-cards"><div className="pair-cards cta-s"><div className="pair-card-view s1 cta-s"><div {...{ "cta-flip-card": "" }} {...{ "wave-parent-default": "" }} className="cta-card"><div className="cta-front-card s1"><div {...{ "wave-parent-infinity": "" }} {...{ "cta-open": "" }} className="cta-flip-button"><div className="cta-open-svg w-embed"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none">
  <path d="M5 12H19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  <path d="M12 5V19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></div><div className="text-elements cta-card-s"><div className="headline-wrapper cta-card-s"><h2 className="headline-h3">For Artists</h2></div></div><div className="open-form full-w"><div {...{ "jelly-hover-parent": "" }} {...{ "view-item": "false" }} {...{ "data-wf--main-button--variant": "l-full-width" }} className="main-button-wrapper w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f"><a {...{ "jelly-hover": "" }} {...{ "wave-parent-infinity": "" }} aria-label="Join Hiffi" href="/signup" className="main-button w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f w-inline-block"><div>Join Hiffi</div><div aria-hidden="true" className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></a></div></div></div><div className="cta-back-card blue"><div {...{ "wave-parent-infinity": "" }} {...{ "cta-close": "" }} className="cta-flip-button close"><div className="cta-open-svg w-embed"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none">
  <path d="M5 12H19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  <path d="M12 5V19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></div><div className="cta-card-descript"><p className="body-medium-m">Hiffi was built to change how independent artists get discovered. Share music, videos, freestyles, cyphers, beat showcases, mixtapes, and exclusive releases on a platform designed for creators — rooted in hip-hop culture.<br/><br/>Whether you&apos;re underground or established, Hiffi amplifies your voice and helps you connect with fans who genuinely care about your work.</p></div><div className="open-form full-w"><div {...{ "jelly-hover-parent": "" }} {...{ "view-item": "false" }} {...{ "data-wf--main-button--variant": "l-full-width" }} className="main-button-wrapper w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f"><a {...{ "jelly-hover": "" }} {...{ "wave-parent-infinity": "" }} aria-label="Join Hiffi" href="/signup" className="main-button w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f w-inline-block"><div>Join Hiffi</div><div aria-hidden="true" className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></a></div></div></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} {...{ "change-color": "" }} className="wave-line-default cta-s"></div></div></div></div><div className="pair-card-view s2 cta-s"><div {...{ "cta-flip-card": "" }} {...{ "wave-parent-default": "" }} className="cta-card"><div className="cta-front-card s2"><div {...{ "wave-parent-infinity": "" }} {...{ "cta-open": "" }} className="cta-flip-button"><div className="cta-open-svg w-embed"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none">
  <path d="M5 12H19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  <path d="M12 5V19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></div><div className="text-elements cta-card-s"><div className="headline-wrapper cta-card-s"><h2 className="headline-h3">Free for <br/>Fans</h2></div></div><div className="open-form full-w"><div {...{ "jelly-hover-parent": "" }} {...{ "view-item": "false" }} {...{ "data-wf--main-button--variant": "l-full-width" }} className="main-button-wrapper w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f"><a {...{ "jelly-hover": "" }} {...{ "wave-parent-infinity": "" }} aria-label="Join Hiffi" href="/signup" className="main-button w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f w-inline-block"><div>Join Hiffi</div><div aria-hidden="true" className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></a></div></div></div><div className="cta-back-card orange"><div {...{ "wave-parent-infinity": "" }} {...{ "cta-close": "" }} className="cta-flip-button close"><div className="cta-open-svg w-embed"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none">
  <path d="M5 12H19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  <path d="M12 5V19" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></div><div className="cta-card-descript"><p className="body-medium-m">For fans, Hiffi is free — giving you unlimited access to discover new artists, connect with your favorites, and explore music on your terms.<br/><br/>Find podcasts, producer showcases, live performances, and emerging talent from local and global communities. Discovery that feels human.</p></div><div className="open-form full-w"><div {...{ "jelly-hover-parent": "" }} {...{ "view-item": "false" }} {...{ "data-wf--main-button--variant": "l-full-width" }} className="main-button-wrapper w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f"><a {...{ "jelly-hover": "" }} {...{ "wave-parent-infinity": "" }} aria-label="Join Hiffi" href="/signup" className="main-button w-variant-191f9b66-4dd5-58af-264e-0b9c03f22b9f w-inline-block"><div>Join Hiffi</div><div aria-hidden="true" className="wave-area"><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div><div {...{ "data-expand": "1.5" }} className="wave-line-infinity"></div></div></a></div></div></div><div className="wave-area"><div {...{ "data-expand": "1.5" }} {...{ "change-color": "" }} className="wave-line-default cta-s"></div></div></div></div></div><div className="cta-js w-embed w-script"></div></div></div>
    </section>
  );
}
